### ISSUE TITLE
problema con el botón "Restaurar"

### ISSUE THREAD

**Issue by YkBastidas** [YkBastidas/ABR-Deliveries#7]
### Branch: FE-PP1 -> /client/src/containers/FormContainer.jsx

**linea 175:**
`<Button action={console.log(this.props.newUser)} type={"warning"} title={"Restaurar"}/>`

### Branch: FE-PP1 -> /client/src/components/Button.jsx
```
const Button = props => {
  return (
    <button
      className={
        props.type === "primary" ? "btn btn-primary" : "btn btn-warning"
      }
      onClick={props.action}
      style={props.buttonstyle}
    >
      {props.title}
    </button>
  );
}; 
```
El problema está en que el botón no ejecuta la propiedad onClick, la cual es llamada como una propiedad de la clase Button, y en Button tomo esas props. como el valor de onClick, el botón debería regresar por consola las propiedades del newUser (lo que está en el form) al hacer click, pero regresa las propiedades cada vez que se alteran, no cuando se da click, no entiendo por qué.

**Nota:** La función del botón es restaurar el estado de cada input del formulario a un string vacío (""), tengo `console.log(this.props.newUser)` para ver lo que devuelve por consola e identificar el error.

**Comment by reinel215** [comment]
verga ni idea

**Comment by YkBastidas** [comment]
Problema solucionado en el siguiente commit:
[https://github.com/YkBastidas/ABR-Deliveries/commit/cd79ccaa59db09e7310619fa8ca8f6acc0b34852](url)
Los "values" de los inputs no estaban llamando correctamente a las props del padre ya que estaba `this.props.name` en vez de `this.props.existingUser.name` al arreglar eso el botón funciono perfecto
